- name: Add keys to known_hosts
  hosts: localhost
  connection: local
  tasks:
    - name: ssh keyscan bastion hosts from localhost
      delegate_to: localhost
      ansible.builtin.lineinfile:
        dest: ~/.ssh/known_hosts
        create: 'yes'
        state: present
        mode: '0600'
        line: "{{ item }}"
      loop:
        - "gateway.autodotes.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOfKLH2uVXzhXlEnAuVeAFHl80zm/hp7rmQyY7vJB5VF"
