---
- name: Add MSSQL yum repo
  tags: prereqs
  ansible.builtin.get_url:
      url: "{{ mssql_repo_url }}"
      dest: "/etc/yum.repos.d/{{ mssql_repo_name }}.repo"
      mode: "0644"

- name: Install MSSQL
  tags: install
  ansible.builtin.yum:
    name: mssql-server
    state: present

- name: Check if service exists
  tags: install
  ansible.builtin.stat:
    path: /usr/lib/systemd/system/mssql-server.service
  register: r_mssql_service

- name: Configure MSSQL
  tags: configure
  when: not r_mssql_service.stat.exists
  environment:
    ACCEPT_EULA: "Y"
    MSSQL_PID: "{{ mssql_pid }}"
    MSSQL_SA_PASSWORD: "{{ mssql_sa_pwd }}"
    MSSQL_TCP_PORT: "{{ mssql_tcp_port }}"
  ansible.builtin.command: /opt/mssql/bin/mssql-conf -n setup

- name: Install packages
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Install packages
  ansible.builtin.service:
    name: firewalld
    state: started

- name: Permit traffic in public zone for mssql service
  tags: configure
  ansible.posix.firewalld:
    zone: public
    port: 1433/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Add developer tools
  tags: configure
  when: mssql_tools_include
  include_tasks: tools.yml
  vars:
    mssql_tools_users: 
      - "{{ ansible_user }}"
