---
- name: Generate Let's Encrypt account key
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_account_key }}"

- name: Generate Let's Encrypt private key
  community.crypto.openssl_privatekey:
    path: "/etc/letsencrypt/keys/{{ acme_domain_name }}.key"

- name: Generate Let's Encrypt CSR
  community.crypto.openssl_csr:
    path: "/etc/letsencrypt/csrs/{{ acme_domain_name }}.csr"
    privatekey_path: "/etc/letsencrypt/keys/{{ acme_domain_name }}.key"
    common_name: "{{ acme_domain_name }}"

- name: Begin Let's Encrypt challenges
  register: r_acme_challenge
  community.crypto.acme_certificate:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    terms_agreed: 1
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ acme_domain_name }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ acme_domain_name }}.pem"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ acme_domain_name }}.pem"
    remaining_days: 91

- name: Create .well-known/acme-challenge directory
  ansible.builtin.file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Implement http-01 challenge files
  ansible.builtin.copy:
    content: "{{ r_acme_challenge['challenge_data'][domain_name]['http-01']['resource_value'] }}"
    dest: "/var/www/html/{{ r_acme_challenge['challenge_data'][domain_name]['http-01']['resource'] }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Complete Let's Encrypt challenges
  community.crypto.acme_certificate:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ acme_domain_name }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ acme_domain_name }}.pem"
    chain_dest: "{{ letsencrypt_certs_dir }}/chain_{{ acme_domain_name }}.pem"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ acme_domain_name }}.pem"
    data: "{{ r_acme_challenge }}"

- name: "Update nginx ssl cert | {{ acme_domain_name }}"
  notify: Restart nginx
  ansible.builtin.lineinfile:
    path: "/etc/nginx/sites-available/{{ acme_domain_name }}.conf"
    regexp: "^(.*)ssl_certificate /etc/letsencrypt"
    line: "\tssl_certificate {{ letsencrypt_certs_dir }}/fullchain_{{ acme_domain_name }}.pem;"

- name: "Update nginx ssl key | {{ acme_domain_name }}"
  notify: Restart nginx
  ansible.builtin.lineinfile:
    path: "/etc/nginx/sites-available/{{ acme_domain_name }}.conf"
    regexp: "^(.*)ssl_certificate_key /etc/letsencrypt"
    line: "\tssl_certificate_key /etc/letsencrypt/keys/{{ acme_domain_name }}.key;"