---
- hosts: "{{ _hosts | default(omit) }}"
  name: Update demo site
  become: true

  vars:
    site_root: /usr/share/nginx/demo

  tasks:
    # Avoid an event loop when restoring site from tar
    - name: Stop path and service
      loop:
        - "{{ systemd_nginx_path_unit_name }}.path"
        - "{{ systemd_nginx_service_name }}.service"
      loop_control:
        loop_var: unit
      ansible.builtin.systemd_service:
        name: "{{ unit }}"
        state: stopped
        
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://artifacts.autodotes.com/demo-site.tar.gz
        dest: "{{ site_root | dirname }}"
        remote_src: yes
        validate_certs: false

    - name: Restart nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: true

    - name: Start path and service
      loop:
        - "{{ systemd_nginx_path_unit_name }}.path"
        - "{{ systemd_nginx_service_name }}.service"
      loop_control:
        loop_var: unit
      ansible.builtin.systemd_service:
        name: "{{ unit }}"
        enabled: true
        state: started
