---
- hosts: "{{ _hosts | default(omit) }}"
  name: Update demo site
  become: true

  vars:
    site_root: /usr/share/nginx/demo
    site_tar_url: https://artifacts.autodotes.com/demo-site.tar.gz
    systemd_nginx_path_unit_name: demosite
    systemd_nginx_service_name: deploydemosite

  tasks:
    # Avoid an event loop when restoring site from tar
    - name: Stop path monitor
      ansible.builtin.systemd_service:
        name: "{{ systemd_nginx_path_unit_name }}.path"
        state: stopped

    - name: Clean destination directory
      ansible.builtin.file:
        name: "{{ site_root }}"
        state: absent
        
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: "{{ site_tar_url }}"
        dest: "{{ site_root | dirname }}"
        remote_src: yes
        validate_certs: false

    - name: Restart nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: true

    - name: Restart path monitor
      ansible.builtin.systemd_service:
        name: "{{ systemd_nginx_path_unit_name }}.path"
        enabled: true
        state: started
