---
- hosts: "{{ _hosts | default(omit) }}"
  name: Update demo site
  become: true

  vars:
    site_root: /usr/share/nginx/demo
    site_tar_url: https://artifacts.autodotes.com/demo-site.tar.gz
    systemd_nginx_path_unit_name: demosite
    systemd_nginx_service_name: deploydemosite

  tasks:
    # Avoid an event loop when restoring site from tar
    - name: Stop path monitor
      ansible.builtin.systemd_service:
        name: "{{ systemd_nginx_path_unit_name }}.path"
        state: stopped

    - name: Clean destination directory
      ansible.builtin.file:
        name: "{{ site_root }}"
        state: absent
        
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: "{{ site_tar_url }}"
        dest: "{{ site_root | dirname }}"
        remote_src: yes
        validate_certs: false

    - name: Restart nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: true

    - name: Restart path monitor
      ansible.builtin.systemd_service:
        name: "{{ systemd_nginx_path_unit_name }}.path"
        enabled: true
        state: started

    - name: Get Host id
      ansible.builtin.set_fact:
        awx_host_id: "{{ lookup('ansible.controller.controller_api', 'hosts', query={'name': inventory_hostname, 'inventory_id': awx_inventory_id}, expect_one=true) }}"

    # - name: Retrieve Job Summaries
    #   ansible.builtin.uri:
    #     url: https://{{ lookup('env', 'TOWER_HOST') }}/api/v2/hosts/{{ host_details.json.results[0].id }}/job_host_summaries/?job__job_template_id={{ awx_job_template_id }}&created__regex={{ ansible_date_time.date }}  # noqa yaml[line-length]
    #     user: "{{ lookup('env', 'TOWER_USERNAME') }}"
    #     password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    #     force_basic_auth: true
    #     method: "GET"
    #     status_code: "200"
    #     validate_certs: false
    #   check_mode: false
    #   register: job_details

    # - name: Counter value of job runs on host today
    #   ansible.builtin.set_fact:
    #     counter: "{{ job_details | regex_findall('processed') | length }}"

    # - name: Create Support Ticket
    #   servicenow.itsm.incident:
    #     state: new
    #     description: "Too many attempted user adds on a single host ({{ counter }} today)"
    #     short_description: "User Creation Policy Violation"
    #     caller: admin
    #     urgency: "medium"
    #     impact: "high"
    #     other:
    #       u_operating_system: "{{ os | default(omit) }}"
    #       u_ip_address: "{{ ip_addr | default(omit) }}"
    #       u_vm_name: "{{ inventory_hostname | default(omit) }}"
    #   register: new_incident
    #   delegate_to: localhost
    #   when: counter|int >=4