---
- name: Use RHEL system roles to configure a machine
  hosts: "{{ ansible_limit | default(omit) }}"
  become: true

  tasks:
    - name: Register machine
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        auto_attach: true

    - name: Enable repositories
      community.general.rhsm_repository:
        name: "{{ rhsm_repos }}"
        state: enabled
