---
- name: Use RHEL system roles to configure a machine
  hosts: "{{ ansible_limit | default(omit) }}"

  tasks:
    - name: Register machine
      become: true
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        auto_attach: true
