---
- name: Install MS SQL Server on RHEL
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: true
  become: true

  tasks:
    - name: Setup MSSQL
      vars:
        mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
        mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
        mssql_accept_microsoft_sql_server_standard_eula: true
        mssql_version: 2019
        mssql_password: "{{ sql_sa_password }}"
        mssql_edition: Evaluation
      ansible.builtin.include_role:
        name: microsoft.sql.server

    - name: Install packages
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Install packages
      ansible.builtin.service:
        name: firewalld
        state: started

    - name: Permit traffic in public zone for mssql service
      tags: configure
      ansible.posix.firewalld:
        zone: public
        port: 1433/tcp
        permanent: true
        immediate: true
        state: enabled
