---
# acme_email: acme-sa@example.com # e-mail address to receive acme notifications
# acme_domain_name: ansible.example.com # certificate common name
# acme_private_ip: 192.168.0.x # private ip address for reverse proxy to direct traffic
acme_letsencrypt_dir: /etc/letsencrypt
acme_letsencrypt_keys_dir: "{{ acme_letsencrypt_dir }}/keys"
acme_letsencrypt_csrs_dir: "{{ acme_letsencrypt_dir }}/csrs"
acme_letsencrypt_certs_dir: "{{ acme_letsencrypt_dir }}/certs"
acme_letsencrypt_account_key: "{{ acme_letsencrypt_dir }}/account/account.key"
acme_required_dirs:
  - "{{ acme_letsencrypt_dir }}"
  - "{{ acme_letsencrypt_keys_dir }}"
  - "{{ acme_letsencrypt_csrs_dir }}"
  - "{{ acme_letsencrypt_certs_dir }}"

acme_valid_days: "30" # if expiring in <= acme_valid_days, generate new cert
acme_site_root: "/var/www/html/{{ acme_domain_name }}" # directory for site root if proxy not used
