---
- name: Configure site with ssl on nginx reverse proxy
  hosts: "{{ _host | default('omit') }}"
  gather_facts: false
  become: true

  tasks:
    - name: Create site with ssl # noqa: var-naming[no-role-prefix]
      when: _domains is not defined
      ansible.builtin.include_role:
        name: nginx_proxy_acme
      vars:
        acme_domain_name: "{{ _domain }}"
        acme_email: "{{ _email }}"

    - name: Create site(s) with ssl # noqa: var-naming[no-role-prefix]
      when: _domains is defined
      loop: "{{ _domains }}"
      loop_control:
        loop_var: domain
        label: "{{ domain.name }}=>{{ domain.private_ip | default('proxy') }}"
      ansible.builtin.include_role:
        name: nginx_proxy_acme
      vars:
        acme_domain_name: "{{ domain.name }}"
        acme_email: "{{ _email }}"
        acme_private_ip: "{{ domain.private_ip | default(omit) }}"
