---
- name: Consume data
  hosts: localhost
  become: false
  gather_facts: false

  # This is my API definition #
  # Each *_query variable should be defined at the Job Template level #
  vars:
    # output: "{{ (lookup('file', 'vars/movies.json') | from_json).results }}"
    # record_count_query: "length([])"
    # titles_query: "[].title"
    # latest_query: "sort_by([], &release_date) | [0]"
    record_count: "{{ output | to_json | from_json |  json_query(record_count_query) }}"
    titles: "{{ output | to_json | from_json |  json_query(titles_query) }}"
    latest: "{{ output | to_json | from_json | json_query(latest_query) }}"

  tasks:
    - name: Assert required outputs
      ansible.builtin.assert:
        that:
          - record_count_query is defined
          - titles_query is defined
          - latest_query is defined

    - name: Debug record_count
      ansible.builtin.debug:
        msg: "record_count: {{ record_count }}"

    - name: Debug titles
      ansible.builtin.debug:
        msg: "titles: {{ titles }}"

    - name: Debug latest
      ansible.builtin.debug:
        msg: "latest: {{ latest }}"
