---
- name: Basic fact gathering playbook
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Gather the package facts
      become: true
      ansible.builtin.package_facts:
        manager: auto

    - name: Map to builder compose input
      ansible.builtin.set_fact:
        builder_compose_pkgs: "{{ ansible_facts.packages.keys() | list }}"

    - name: Print the result
      ansible.builtin.debug:
        var: builder_compose_pkgs
