---
- name: Basic fact gathering playbook
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: false

  tasks:
    - name: Gather the package facts
      become: true
      ansible.builtin.package_facts:
        manager: auto

    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages